language: node_js
node_js: node
sudo: required
services:
  - docker

before_install:
  - docker build -t bamas/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true bamas/docker-react npm run test
